### PR TITLE
Develop into master (code review)

### PR DESCRIPTION
**Pull request by benjaoming**
@aronasorman in case you've requested code reviews or assistance from others, feel free to assign 'em here :+1:

### CODE REVIEW

**Comment by aronasorman** [comment]
@benjaoming yup! I'll have to add more documentation to help reviewers, should be done by today

**Comment by aronasorman** [comment]
Pushed more changes! Still no documentation, but insantiating `InMemClient` and then calling`client.schedule` should work. There's still a bug regarding scheduling more than 3 jobs (with a corresponding failing test for that), but otherwise basic things should work now.

**Comment by aronasorman** [comment]
Also uploaded the requirements for testing (`pytest`). Otherwise this should work out of the box with just the standard library.

**Comment by indirectlylit** [comment]
uh oh – looks `master` and `develop` are out-of-sync

**Comment by benjaoming** [comment]
yup @indirectlylit, haven't investigated, but I'll figure it out... not sure what branch strategy @aronasorman wants, would suggest NOT having a develop branch -- see #23

**Comment by benjaoming** [comment]
There is a conflict in `src/barbequeue/storage/backends/inmem.py`, so something must have been changed at some point in `master`.

Once again: Please consider a simple branch strategy by removing the `develop` branch when it adds unnecessary complexity to development and maintenance of the repo.

**Comment by benjaoming** [comment]
I can merge develop into master locally w/o conflicts. Not sure what strategy Github uses.

**Pull request closed without merging**
