### PR TITLE
Use multiprocessing by default, but fall back to threading.

### PR DESCRIPTION
**Pull request by rtibbles**
Adds a compatibility layer to try to use Python multiprocessing when possible.

### CODE REVIEW

**Comment by benjaoming** [comment]
That sounds really interesting!

For this type of change, it would be useful, if the tests were fixed, firstly. Perhaps you can recruit an certain expert to ensure the prior existence of functional tests -- as in tests that aren't broken :)

**Comment by rtibbles** [comment]
Interesting, they all passed locally.

**Comment by rtibbles** [comment]
Ahh... yeah, that's not ideal. I thought because it was namespaced in iceqube it would be ok!

**Comment by aronasorman** [comment]
Normally it's namespaced, but when you do an `import threading` within the `threading` module itself, it'll import itself! So it actually did a recursive import, and python silently exits the import if it detects that.

**Comment by rtibbles** [comment]
:man_facepalming:

**Comment by aronasorman** [comment]
Pushed as Iceqube 0.0.5!

**Comment by rtibbles** [comment]
Woot!

**Comment by benjaoming** [comment]
Awesome work @aronasorman and @rtibbles :)

**Pull request merged**
